name: Bug report
description: File a bug report related with the extension.
title: "[BUG]: "
labels: ["bug". "traige"]
asignees: 
 - glitchedslimy
body:
  - type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can I reach you?
      placeholder: ex. email@example.com or @username on discord
      validations:
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue you are facing.
      placeholder: ex. I was trying to do X and Y happened instead of Z, put screenshots if you can!.
      validations:
        required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the issue?
      options:
        - Low
        - Medium
        - High
        - Critical
      validations:
        required: true
  - type: dropdown
    id: type-of-bug
    attributes:
      label: Type of bug
      description: What type of bug are you facing?
      options:
        - Performance
        - Visual Bug
        - UI/UX
        - Crash
        - Other
      validations:
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow the Code of Conduct
          required: true