name: Feature Request
description: I have a suggestion for a new feature.
title: "[Feat]: "
labels: ["enhancement", "request"]
assignees:
  - glitchedslimy
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! We appreciate your feedback. Please fill out the form below.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Please describe the feature you would like to see implemented.
      placeholder: Tell us what you're thinking! Include any relevant details. And screenshots if possible!
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or @username on discord.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
